name: WXTRA APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  APK:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi indir
        uses: actions/checkout@v4

      - name: Java 17 kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Gradle kur
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: ZIP'i aç
        run: |
          mkdir project
          unzip -q wxtra.zip -d project

      - name: Gradle projesini bul
        shell: bash
        run: |
          PROJECT_DIR=$(find project -type f -name "settings.gradle" -print -quit)

          if [ -z "$PROJECT_DIR" ]; then
            PROJECT_DIR=$(find project -type f -name "settings.gradle.kts" -print -quit)
          fi

          if [ -z "$PROJECT_DIR" ]; then
            echo "HATA: settings.gradle bulunamadı!"
            exit 1
          fi

          PROJECT_DIR=$(dirname "$PROJECT_DIR")

          echo "Gradle proje klasörü: $PROJECT_DIR"
          echo "PROJECT_DIR=$PROJECT_DIR" >> "$GITHUB_ENV"

      - name: APK oluştur
        run: |
          cd "$PROJECT_DIR"
          gradle assembleDebug --stacktrace

      - name: APK'yı yükle
        uses: actions/upload-artifact@v4
        with:
          name: WXTRA-APK
          path: "project/**/app/build/outputs/apk/debug/*.apk"
          if-no-files-found: error
